[package]
name = "wm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
penrose = { git = "https://github.com/teo8192/penrose", branch = "bugfixes" }
simplelog = "0.11"
log = "0.4"
